const products = [

    { "name": "Oreson Wells", "description": "I am an out of this world rock. I have caused fits of panic from my extraterrestrial aura. I will form an ironclad friendship with those who take the time to stop and smell the rosebuds. My love of jewels may only be rivaled by my passion for skipping on water.", "size": "large", "imageUrl": "/images/meteor-rock.jpg", "price": 5300, "stockQuantity": 56 },
    { "name": "Constance Cobblestone", "description": "I am very shy at first but I'm happy to sit quietly with you if you need some company. I love boardgames and sound of rain.", "size": "small", "imageUrl": "/images/defaultPetRock.jpg", "price": 4499, "stockQuantity": 65 },
    { "name": "Rocky Bouldoa", "description": "I'm a big tough guy but on quiet nights I enjoy reruns of Survivor and Jersey Shore with a nice glass of cheap Merlot.", "size": "large", "imageUrl": "/images/stoner-rock.jpg", "price": 5750, "stockQuantity": 65 },
    { "name": "S'tony", "description": "The S in the name stands for supportive. I will be there through all your hardships. Everyone needs a team player, and S'tony is a friend you can always rely on.", "size": "medium", "imageUrl": "/images/hairy-rock.jpg", "price": 2299, "stockQuantity": 45 },
    { "name": "Ignatius I Igneous", "description": "Although I have suffered from meltdowns in the past, I have managed to stay cool for many eons (despite people mixing up lava and magma).", "size": "small", "imageUrl": "/images/mustache-rock.jpg", "price": 999, "stockQuantity": 65 },
    { "name": "Oz Sideon", "description": "I'm super edgy and always looking sharp. With a cutting wit and dark sense of humor, I'm a rad friend to keep around for laughs and chaos.", "size": "small", "imageUrl": "/images/weird-rock.jpg", "price": 4500, "stockQuantity": 65 },
    { "name": "Lawrence Limestone", "description": "If you need a shoulder to cry on, I'm the rock for you, quite good at handling sedimentality. However, I do not do well with abstract thoughts and prefer when things are more concrete.", "size": "large", "imageUrl": "/images/nest-rock.jpg", "price": 1499, "stockQuantity": 65 },
    { "name": "Googly McGillipuddi", "description": "I suffer from brachiopods lodged in my abdomen but enjoy watching competitive juggling", "size": "small", "imageUrl": "/images/happy-rock.jpg", "price": 7000, "stockQuantity": 65 },
    { "name": "Slade Gibson", "description": "A rock like no other, go home and tell your mother, you have nothing to fear, with Slade Gibson here.", "size": "large", "imageUrl": "/images/blonde-rock.jpg", "price": 6999, "stockQuantity": 65 },
    { "name": "Corey the Coprolite", "description": "Great support for when you're feeling icky! A paleontology enthusiast, I'll help you dig yourself out of that hole. Also good at reminding you to eat.", "size": "medium", "imageUrl": "/images/defaultPetRock.jpg", "price": 3799, "stockQuantity": 65 },
    { "name": "Doug Slate", "description": "Some people think I’m pretty schisty and oppressive but my friends know I’m really a gneiss guy. I’m very meta though so please be kind.", "size": "small", "imageUrl": "/images/punk-rock.jpg", "price": 4499, "stockQuantity": 65 },
    { "name": "Ruprect", "description": "I will always believe in you no matter what. I always like to look on the bright side of things!", "size": "small", "imageUrl": "/images/giddy-rock.jpg", "price": 1999, "stockQuantity": 65 },
    { "name": "Pomme Granite", "description": "I was magma before it was cool. I am a solid companion not weighed down by sedimentary concerns.", "size": "small", "imageUrl": "/images/frida-rock.jpg", "price": 4499, "stockQuantity": 65 },
    { "name": "Chip", "description": "I'm a little different then all the rest.. I don't really fit in. I can be flaky at times. I seem like a shiny dude but I do have a poisonous side.", "size": "small", "imageUrl": "/images/solid-rock.jpg", "price": 999, "stockQuantity": 65 },
    { "name": "Rocky McRockFace", "description": "Sturdy and reliable friend. Really held things together. In a pinch makes a great projectile weapon.", "size": "small", "imageUrl": "/images/bear-rock.jpg", "price": 4500, "stockQuantity": 65 },
    // { "name": "", "description": "", "size": "small", "imageUrl": "/images/defaultPetRock.jpg", "price": 4499, "stockQuantity": 65 },

    { "name": "Oreson Wells", "description": "I am an out of this world rock. I have caused fits of panic from my extraterrestrial aura. I will form an ironclad friendship with those who take the time to stop and smell the rosebuds. My love of jewels may only be rivaled by my passion for skipping on water.", "size": "large", "imageUrl": "/images/meteor-rock.jpg", "price": 5300, "stockQuantity": 56 },
    { "name": "Constance Cobblestone", "description": "I am very shy at first but I'm happy to sit quietly with you if you need some company. I love boardgames and sound of rain.", "size": "small", "imageUrl": "/images/defaultPetRock.jpg", "price": 4499, "stockQuantity": 65 },
    { "name": "Rocky Bouldoa", "description": "I'm a big tough guy but on quiet nights I enjoy reruns of Survivor and Jersey Shore with a nice glass of cheap Merlot.", "size": "large", "imageUrl": "/images/stoner-rock.jpg", "price": 5750, "stockQuantity": 65 },
    { "name": "S'tony", "description": "The S in the name stands for supportive. I will be there through all your hardships. Everyone needs a team player, and S'tony is a friend you can always rely on.", "size": "medium", "imageUrl": "/images/hairy-rock.jpg", "price": 2299, "stockQuantity": 45 },
    { "name": "Ignatius I Igneous", "description": "Although I have suffered from meltdowns in the past, I have managed to stay cool for many eons (despite people mixing up lava and magma).", "size": "small", "imageUrl": "/images/mustache-rock.jpg", "price": 999, "stockQuantity": 65 },
    { "name": "Oz Sideon", "description": "I'm super edgy and always looking sharp. With a cutting wit and dark sense of humor, I'm a rad friend to keep around for laughs and chaos.", "size": "small", "imageUrl": "/images/weird-rock.jpg", "price": 4500, "stockQuantity": 65 },
    { "name": "Lawrence Limestone", "description": "If you need a shoulder to cry on, I'm the rock for you, quite good at handling sedimentality. However, I do not do well with abstract thoughts and prefer when things are more concrete.", "size": "large", "imageUrl": "/images/nest-rock.jpg", "price": 1499, "stockQuantity": 65 },
    { "name": "Googly McGillipuddi", "description": "I suffer from brachiopods lodged in my abdomen but enjoy watching competitive juggling", "size": "small", "imageUrl": "/images/happy-rock.jpg", "price": 7000, "stockQuantity": 65 },
    { "name": "Slade Gibson", "description": "A rock like no other, go home and tell your mother, you have nothing to fear, with Slade Gibson here.", "size": "large", "imageUrl": "/images/blonde-rock.jpg", "price": 6999, "stockQuantity": 65 },
    { "name": "Corey the Coprolite", "description": "Great support for when you're feeling icky! A paleontology enthusiast, I'll help you dig yourself out of that hole. Also good at reminding you to eat.", "size": "medium", "imageUrl": "/images/defaultPetRock.jpg", "price": 3799, "stockQuantity": 65 },
    { "name": "Doug Slate", "description": "Some people think I’m pretty schisty and oppressive but my friends know I’m really a gneiss guy. I’m very meta though so please be kind.", "size": "small", "imageUrl": "/images/punk-rock.jpg", "price": 4499, "stockQuantity": 65 },
    { "name": "Ruprect", "description": "I will always believe in you no matter what. I always like to look on the bright side of things!", "size": "small", "imageUrl": "/images/giddy-rock.jpg", "price": 1999, "stockQuantity": 65 },
    { "name": "Pomme Granite", "description": "I was magma before it was cool. I am a solid companion not weighed down by sedimentary concerns.", "size": "small", "imageUrl": "/images/frida-rock.jpg", "price": 4499, "stockQuantity": 65 },
    { "name": "Chip", "description": "I'm a little different then all the rest.. I don't really fit in. I can be flaky at times. I seem like a shiny dude but I do have a poisonous side.", "size": "small", "imageUrl": "/images/solid-rock.jpg", "price": 999, "stockQuantity": 65 },
    { "name": "Rocky McRockFace", "description": "Sturdy and reliable friend. Really held things together. In a pinch makes a great projectile weapon.", "size": "small", "imageUrl": "/images/bear-rock.jpg", "price": 4500, "stockQuantity": 65 },

]

module.exports = products