const productInOrders = [{ "quantity": 1 },
{ "quantity": 2 },
{ "quantity": 1 },
{ "quantity": 2 },
{ "quantity": 1 },
{ "quantity": 2 },
{ "quantity": 2 },
{ "quantity": 2 },
{ "quantity": 3 },
{ "quantity": 1 },
{ "quantity": 2 },
{ "quantity": 2 },
{ "quantity": 2 },
{ "quantity": 1 },
{ "quantity": 1 },
{ "quantity": 1 },
{ "quantity": 1 },
{ "quantity": 1 },
{ "quantity": 2 },
{ "quantity": 3 },
{ "quantity": 1 },
{ "quantity": 2 },
{ "quantity": 3 },
{ "quantity": 3 },
{ "quantity": 1 },
{ "quantity": 1 },
{ "quantity": 3 },
{ "quantity": 2 },
{ "quantity": 3 },
{ "quantity": 2 },
]

module.exports = productInOrders