const shippingAddresses = [{ "email": "tgregolin0@springer.com", "firstName": "Travers", "lastName": "Gregolin", "streetAddress": "7097 Jenna Point", "city": "Cleveland", "state": "OH", "zipCode": "44105" },
{ "email": "ajeffryes1@ibm.com", "firstName": "Amelia", "lastName": "Jeffryes", "streetAddress": "04 Troy Way", "city": "Burbank", "state": "CA", "zipCode": "91520" },
{ "email": "jarpino2@boston.com", "firstName": "Jennine", "lastName": "Arpino", "streetAddress": "2 Independence Center", "city": "Wichita Falls", "state": "TX", "zipCode": "76310" },
{ "email": "wboram3@fc2.com", "firstName": "Waring", "lastName": "Boram", "streetAddress": "8 Glacier Hill Court", "city": "Denver", "state": "CO", "zipCode": "80299" },
{ "email": "asimeonov4@theglobeandmail.com", "firstName": "Alexandrina", "lastName": "Simeonov", "streetAddress": "2497 Karstens Plaza", "city": "Rochester", "state": "NY", "zipCode": "14652" },
{ "email": "mtutchener5@addtoany.com", "firstName": "Malinde", "lastName": "Tutchener", "streetAddress": "69 Warbler Alley", "city": "Jacksonville", "state": "FL", "zipCode": "32209" },
{ "email": "sdumbare6@oakley.com", "firstName": "Suzanna", "lastName": "Dumbare", "streetAddress": "5 Armistice Alley", "city": "Topeka", "state": "KS", "zipCode": "66667" },
{ "email": "hgrosvenor7@elegantthemes.com", "firstName": "Halsey", "lastName": "Grosvenor", "streetAddress": "2504 Barby Point", "city": "Albany", "state": "NY", "zipCode": "12247" },
{ "email": "ylaminman8@cnet.com", "firstName": "York", "lastName": "Laminman", "streetAddress": "1376 Sheridan Court", "city": "Springfield", "state": "MA", "zipCode": "01152" },
{ "email": "mreditt9@disqus.com", "firstName": "Moritz", "lastName": "Reditt", "streetAddress": "3986 Kedzie Center", "city": "Houston", "state": "TX", "zipCode": "77228" },
{ "email": "mbosencea@zimbio.com", "firstName": "Maximilian", "lastName": "Bosence", "streetAddress": "92 Boyd Alley", "city": "Madison", "state": "WI", "zipCode": "53779" },
{ "email": "bolohanb@google.co.uk", "firstName": "Britt", "lastName": "Olohan", "streetAddress": "8637 Grayhawk Parkway", "city": "Great Neck", "state": "NY", "zipCode": "11024" },
{ "email": "gheitzc@howstuffworks.com", "firstName": "Gloriana", "lastName": "Heitz", "streetAddress": "48580 Harper Road", "city": "Sacramento", "state": "CA", "zipCode": "94207" },
{ "email": "jcouvertd@rambler.ru", "firstName": "Juliane", "lastName": "Couvert", "streetAddress": "0875 Karstens Street", "city": "Sioux Falls", "state": "SD", "zipCode": "57188" },
{ "email": "farkleye@jalbum.net", "firstName": "Finn", "lastName": "Arkley", "streetAddress": "91941 Morrow Plaza", "city": "Saint Louis", "state": "MO", "zipCode": "63131" },
{ "email": "dsivewrightf@is.gd", "firstName": "Delores", "lastName": "Sivewright", "streetAddress": "2 Blackbird Drive", "city": "Washington", "state": "DC", "zipCode": "20442" },
{ "email": "rrichingsg@shop-pro.jp", "firstName": "Rheba", "lastName": "Richings", "streetAddress": "13 Grayhawk Terrace", "city": "Fresno", "state": "CA", "zipCode": "93704" },
{ "email": "wjoseyh@home.pl", "firstName": "Walsh", "lastName": "Josey", "streetAddress": "273 Onsgard Alley", "city": "Washington", "state": "DC", "zipCode": "20508" },
{ "email": "dmallochi@lycos.com", "firstName": "Deedee", "lastName": "Malloch", "streetAddress": "2158 Talisman Avenue", "city": "Detroit", "state": "MI", "zipCode": "48206" },
{ "email": "nmenguyj@ucoz.com", "firstName": "Norah", "lastName": "Menguy", "streetAddress": "6 Eastwood Road", "city": "Green Bay", "state": "WI", "zipCode": "54313" },
{ "email": "kcleifek@hubpages.com", "firstName": "Kai", "lastName": "Cleife", "streetAddress": "09466 Lakewood Gardens Plaza", "city": "Phoenix", "state": "AZ", "zipCode": "85020" },
{ "email": "scurtaynel@tinypic.com", "firstName": "Salomon", "lastName": "Curtayne", "streetAddress": "01977 Carioca Avenue", "city": "Lexington", "state": "KY", "zipCode": "40596" },
{ "email": "tbasilm@mtv.com", "firstName": "Torrance", "lastName": "Basil", "streetAddress": "70 Emmet Parkway", "city": "Indianapolis", "state": "IN", "zipCode": "46226" },
{ "email": "sspawforthn@google.co.jp", "firstName": "Samuele", "lastName": "Spawforth", "streetAddress": "097 School Court", "city": "Philadelphia", "state": "PA", "zipCode": "19125" },
{ "email": "bbernardto@thetimes.co.uk", "firstName": "Berk", "lastName": "Bernardt", "streetAddress": "86047 Kensington Place", "city": "South Bend", "state": "IN", "zipCode": "46699" },
{ "email": "bmckibbinp@hatena.ne.jp", "firstName": "Boone", "lastName": "McKibbin", "streetAddress": "1 Johnson Hill", "city": "Tacoma", "state": "WA", "zipCode": "98442" },
{ "email": "tsomerscalesq@stumbleupon.com", "firstName": "Tiertza", "lastName": "Somerscales", "streetAddress": "0 Southridge Lane", "city": "Odessa", "state": "TX", "zipCode": "79769" },
{ "email": "mweirr@opensource.org", "firstName": "Maryjo", "lastName": "Weir", "streetAddress": "38274 Thackeray Point", "city": "Indianapolis", "state": "IN", "zipCode": "46239" },
{ "email": "wallbuts@naver.com", "firstName": "Weylin", "lastName": "Allbut", "streetAddress": "44 Mayfield Parkway", "city": "Naples", "state": "FL", "zipCode": "33961" },
{ "email": "igranet@amazonaws.com", "firstName": "Isaac", "lastName": "Grane", "streetAddress": "1 Clemons Street", "city": "Naples", "state": "FL", "zipCode": "34108" },
{ "email": "bdikelinu@cornell.edu", "firstName": "Bordy", "lastName": "Dikelin", "streetAddress": "3220 Del Mar Parkway", "city": "Boulder", "state": "CO", "zipCode": "80328" },
{ "email": "rtodariniv@google.co.jp", "firstName": "Ronnie", "lastName": "Todarini", "streetAddress": "93 Lindbergh Lane", "city": "Seattle", "state": "WA", "zipCode": "98133" },
{ "email": "jsywellw@economist.com", "firstName": "Junette", "lastName": "Sywell", "streetAddress": "7 Raven Junction", "city": "Beaufort", "state": "SC", "zipCode": "29905" },
{ "email": "gchecklinx@washingtonpost.com", "firstName": "Guinna", "lastName": "Checklin", "streetAddress": "0141 Lighthouse Bay Place", "city": "Panama City", "state": "FL", "zipCode": "32405" },
{ "email": "agrundwatery@unblog.fr", "firstName": "Aksel", "lastName": "Grundwater", "streetAddress": "0970 Hollow Ridge Drive", "city": "El Paso", "state": "TX", "zipCode": "79923" },
{ "email": "kmattersonz@umn.edu", "firstName": "Kelly", "lastName": "Matterson", "streetAddress": "70 Briar Crest Court", "city": "Great Neck", "state": "NY", "zipCode": "11024" },
{ "email": "amcwhorter10@unblog.fr", "firstName": "Abram", "lastName": "McWhorter", "streetAddress": "56739 Clemons Place", "city": "Fort Worth", "state": "TX", "zipCode": "76121" },
{ "email": "jgreener11@webs.com", "firstName": "Jorge", "lastName": "Greener", "streetAddress": "191 Northridge Road", "city": "Seattle", "state": "WA", "zipCode": "98133" },
{ "email": "cscrannage12@rakuten.co.jp", "firstName": "Chanda", "lastName": "Scrannage", "streetAddress": "9 Doe Crossing Terrace", "city": "Chicago", "state": "IL", "zipCode": "60686" },
{ "email": "tdellcasa13@icq.com", "firstName": "Tonya", "lastName": "Dell Casa", "streetAddress": "822 Elka Terrace", "city": "Atlanta", "state": "GA", "zipCode": "30392" },
{ "email": "epotts14@tinyurl.com", "firstName": "Ekaterina", "lastName": "Potts", "streetAddress": "5893 Birchwood Drive", "city": "Portland", "state": "OR", "zipCode": "97201" },
{ "email": "vbatistelli15@google.com", "firstName": "Velma", "lastName": "Batistelli", "streetAddress": "235 Kings Junction", "city": "Miami", "state": "FL", "zipCode": "33134" },
{ "email": "scogar16@columbia.edu", "firstName": "Samaria", "lastName": "Cogar", "streetAddress": "44 Cottonwood Road", "city": "Shreveport", "state": "LA", "zipCode": "71130" },
{ "email": "rdomokos17@nifty.com", "firstName": "Rahal", "lastName": "Domokos", "streetAddress": "91368 Hanover Point", "city": "Atlanta", "state": "GA", "zipCode": "30301" },
{ "email": "mbesnard18@amazon.com", "firstName": "Matilda", "lastName": "Besnard", "streetAddress": "8 Nova Drive", "city": "Kansas City", "state": "MO", "zipCode": "64130" },
{ "email": "jsevern19@msn.com", "firstName": "Junie", "lastName": "Severn", "streetAddress": "3290 Banding Drive", "city": "Evansville", "state": "IN", "zipCode": "47712" },
{ "email": "ecroyden1a@columbia.edu", "firstName": "Ealasaid", "lastName": "Croyden", "streetAddress": "0 Mendota Terrace", "city": "Alexandria", "state": "VA", "zipCode": "22301" },
{ "email": "agolborne1b@weebly.com", "firstName": "Ardeen", "lastName": "Golborne", "streetAddress": "59 Park Meadow Pass", "city": "Lakeland", "state": "FL", "zipCode": "33805" },
{ "email": "rkimbell1c@alexa.com", "firstName": "Rafaelita", "lastName": "Kimbell", "streetAddress": "78238 Sutherland Trail", "city": "Memphis", "state": "TN", "zipCode": "38109" },
{ "email": "dwaples1d@bbc.co.uk", "firstName": "Dolli", "lastName": "Waples", "streetAddress": "2 Ruskin Crossing", "city": "Alpharetta", "state": "GA", "zipCode": "30022" }]


module.exports = shippingAddresses